import Link from 'next/link';

export default function Terms() {
  return (
    <main className="min-h-screen p-8 bg-[#FDFBF7]">
      <div className="max-w-3xl mx-auto bg-white rounded-2xl shadow-sm border border-[#E7E5E4] p-8 md:p-12">
        <div className="mb-8">
          <Link href="/" className="text-[#1C1917] font-medium hover:underline">
            ← Back to Home
          </Link>
        </div>

        <h1 className="text-3xl font-bold text-[#1C1917] mb-8">Terms of Service</h1>

        <div className="p-4 bg-amber-50 border border-amber-200 rounded-lg text-amber-800 text-xs text-left mb-8">
            <p className="font-bold mb-1">DISCLAIMER:</p>
            <p>
              This tool is for educational and personal use only. By using this tool, you agree that you are solely responsible for any legal consequences that may arise from modifying proprietary files. 
              We do not endorse removing watermarks from commercial projects without a proper license. 
              Please support the developers of Spline by purchasing a subscription if you use their tool professionally.
            </p>
        </div>

        <div className="prose prose-stone max-w-none space-y-6 text-[#57534E]">
          <section>
            <h2 className="text-xl font-bold text-[#1C1917] mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing and using FetchSub ("the Service"), you accept and agree to be bound by the terms and provision of this agreement.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1C1917] mb-3">2. Description of Service</h2>
            <p>
              FetchSub provides a client-side tool for modifying .splinecode files. The Service operates entirely within your web browser; no files are uploaded to our servers.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1C1917] mb-3">3. User Responsibility & Liability</h2>
            <p>
              You acknowledge that you are solely responsible for how you use the modified files generated by this Service. FetchSub is intended for educational purposes only.
            </p>
            <p className="font-medium mt-2">
              You agree to indemnify and hold harmless FetchSub, its creators, and maintainers from any claims, damages, legal actions, or liabilities arising from:
            </p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>Your use of the Service.</li>
              <li>Your violation of any third-party rights, including intellectual property rights.</li>
              <li>Your violation of Spline's Terms of Service or End User License Agreement.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1C1917] mb-3">4. Intellectual Property</h2>
            <p>
              This Service does not claim ownership of any files you process. You retain all rights to your content. However, you must ensure you have the legal right to modify any files you process with this tool.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1C1917] mb-3">5. Disclaimer of Warranties</h2>
            <p className="uppercase font-bold text-xs tracking-wide mb-2">READ CAREFULLY</p>
            <p>
              THE SERVICE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SERVICE OR THE USE OR OTHER DEALINGS IN THE SERVICE.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#1C1917] mb-3">6. Modifications to Service</h2>
            <p>
              We reserve the right to modify or discontinue, temporarily or permanently, the Service with or without notice.
            </p>
          </section>
        </div>
        
        <div className="mt-12 pt-8 border-t border-[#E7E5E4] text-sm text-[#78716C]">
          <p>Last updated: November 2025</p>
        </div>
      </div>
    </main>
  );
}
